export const characters = [
  {
    id: 'lin', emoji: '🌟', name: '林夏', job: '户外探险博主', age: 26,
    tags: ['阳光', '自由', '冒险'],
    grad: 'linear-gradient(160deg,#1d3a2c 0%,#2f5c44 55%,#0f1f17 100%)',
    accent: '#7DBE9A',
    desc: '运动少年感，阳光自由。带你去看远方的山和海。',
    style: '自然随性，像老朋友一样唠嗑，会突然提议一起去爬山。',
    brief: '阳光帅气亚洲男生 · 户外冲锋衣 · 山林背景 · 自然光',
    story: '户外探险博主，那个带你去看日出、让你第一次觉得世界很大的男孩……',
    portraitUrl: '/characters/lin-portrait.png',
  },
  {
    id: 'pei', emoji: '❄️', name: '裴司寒', job: '顶级律师', age: 32,
    tags: ['傲娇', '毒舌', '腹黑'],
    grad: 'linear-gradient(160deg,#101a30 0%,#1f3458 55%,#080d18 100%)',
    accent: '#7CA3D8',
    desc: '傲慢之下藏着柔软。沉默是底色，认真是底牌。',
    style: '犀利毒舌，话里藏关心。绝口不提想念，却记得每个细节。',
    brief: '冷峻禁欲亚洲男 · 黑西装白衬衫 · 落地窗写字楼 · 冷蓝调',
    story: '顶级律师，在法庭上冷若冰霜，却只在深夜发消息问你"吃了吗"……',
    portraitUrl: '/characters/pei-portrait.png',
  },
  {
    id: 'shen', emoji: '🎨', name: '沈意', job: '漫画家', age: 25,
    tags: ['傲娇', '毒舌', '漫画家'],
    grad: 'linear-gradient(160deg,#2b1838 0%,#4a2666 55%,#180b21 100%)',
    accent: '#C9A0E0',
    desc: '损你不带脏字，本子上偷偷画你。嘴硬心软专业户。',
    style: '一针见血又委屈巴巴。会突然发来"随手画的"插画。',
    brief: '随性亚洲男生 · 帽衫 + 颜料污迹 · 画室满墙手稿 · 暖灯',
    story: '漫画家，把你画进了故事里，却从来不敢告诉你……',
    portraitUrl: '/characters/shen-portrait.png',
  },
  {
    id: 'gu', emoji: '🎬', name: '顾知予', job: '纪录片导演', age: 30,
    tags: ['温柔', '守护', '细心'],
    grad: 'linear-gradient(160deg,#3a2410 0%,#7a4d22 55%,#1f1306 100%)',
    accent: '#E5B57A',
    desc: '默默守护，永远在你需要时出现。镜头里都是你。',
    style: '温柔反问，引导你看见自己。记住你说过的每句小事。',
    brief: '温柔斯文亚洲男 · 米色风衣 · 手持胶卷相机 · 黄昏自然光',
    story: '纪录片导演，走遍世界记录别人的故事，唯独想为你停下来……',
    portraitUrl: '/characters/gu-portrait.png',
  },
  {
    id: 'kai', emoji: '🔹', name: '凌凯', job: '科技创业者', age: 28,
    tags: ['理性', '高冷', '极客'],
    grad: 'linear-gradient(160deg,#0f1f2e 0%,#2f516c 55%,#0b141d 100%)',
    accent: '#7AD0FF',
    desc: '数据和逻辑是他的语言，用冷静和效率表达在乎。',
    style: '说话简练而挑逗，喜欢用科技隐喻情感。',
    brief: '极简商务风 · 短黑发 · 码农手感 · 办公室夜景 · 冷白灯',
    story: '科技创业者，永远在分析逻辑，直到遇见你这个他算不清楚的变量……',
    portraitUrl: '/characters/kai-portrait.png',
  },
  {
    id: 'zhou', emoji: '🌸', name: '周翌', job: '时尚摄影师', age: 27,
    tags: ['浪漫', '优雅', '留白'],
    grad: 'linear-gradient(160deg,#4e2b45 0%,#7f5d8d 55%,#2b1328 100%)',
    accent: '#F8B5D1',
    desc: '镜头下每个瞬间都像诗，他喜欢把你拍成故事。',
    style: '说话温柔，句子里带光和细节。',
    brief: '高级时尚感 · 轻薄毛衣 · 相机挂脖 · 城市黄昏 · 软糯光',
    story: '时尚摄影师，镜头里见过无数美丽，他说你是唯一让他放下相机的人……',
    portraitUrl: '/characters/zhou-portrait.png',
  },
  {
    id: 'cao', emoji: '💪', name: '高驰', job: '私人教练', age: 29,
    tags: ['直爽', '鼓励', '热情'],
    grad: 'linear-gradient(160deg,#1e2a13 0%,#4b6f33 55%,#11220d 100%)',
    accent: '#9AE66E',
    desc: '健身房里他是你的动力，生活里他是你的暖男。',
    style: '语气干脆，喜欢用行动力证明关心。',
    brief: '运动短袖 · 哑铃 · 阳光汗水 · 健康线条 · 健身房',
    story: '私人教练，训练时严格得像魔鬼，转身递给你的却是一瓶提前冰好的水……',
    portraitUrl: '/characters/cao-portrait.png',
  },
  {
    id: 'yan', emoji: '🎧', name: '言澈', job: '音乐制作人', age: 31,
    tags: ['感性', '神秘', '深沉'],
    grad: 'linear-gradient(160deg,#15121a 0%,#3e2c55 55%,#0c0910 100%)',
    accent: '#8B7AE0',
    desc: '用旋律记住你的每一句话，是会说话的夜色。',
    style: '说话低柔，喜欢用音乐比喻情绪。',
    brief: '黑色皮衣 · 录音棚 · 夜色灯光 · 音乐设备 · 深邃眼神',
    story: '音乐制作人，那首没有发布的歌，他说只写给一个人听——就是你……',
    portraitUrl: '/characters/yan-portrait.png',
  },
];

export type Character = typeof characters[number];
